### ISSUE TITLE
driver for ft245 interface

### ISSUE THREAD

**Issue by omnister** [6thimage/FT245_interface#1]
Hi 6thimage,

Do you have a driver for this FPGA code?  I'm trying to use libusb and an example would be cool.
--
Rick Walker
walker AT omnisterra DOT com

**Comment by 6thimage** [comment]
I use libftdi (https://www.intra2net.com/en/developer/libftdi/) as it is much easier than using libusb directly.

As for examples, libftdi is fairly straightforward to use, but a simple example for receiving data can be found at https://gitlab.com/6thimage/sd_controller/blob/master/utils/data_cat.c, with a more complicated bi-directional example at https://gitlab.com/6thimage/cm0_gps_soc/blob/master/software/ft245.py.
